name: Violet I Johnson
permalink: /:categories/:year/:month/:day/:title
#domain: my-site.github.io
#url: https://my-site.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /      # place folder name if the site is served in a subfolder